### ISSUE TITLE
Thoughts on the possible implementation

### ISSUE THREAD

**Issue by klesun** [klesun/deep-assoc-completion-vscode#1]
The task at hand is to make it possible for a developer to write php code with static typing of associative arrays similar to typescript interfaces.
- Completion/GoTo
- Wrong keys error checks
- Ability to define global type aliases, like [`@psalm-type`](https://github.com/vimeo/psalm/issues/1363)

I considered using hack, but that [does not seem](https://hhvm.com/blog/2018/09/12/end-of-php-support-future-of-hack.html) to be an option anymore in 2k20

First thing to do is to make basic completion from PSALM-ish phpdoc comment and type inference.

I just thought of one thing: what if we declare global types using `.d.ts` files and typescript syntax? Just a random idea, I did not think deep about problems like specifying php classes in this structure...

And here comes another idea: using files with hack syntax for global type defs! These would supposedly have syntax support from the hack plugins out of the box!

**Comment by klesun** [comment]
After discussing with Louis and Mike today, we agreed to use PSALM-ish format for global type definition files, slightly adjusted to give names to types:
```
// same as `@template T` in phpdoc
type Sale<T> = array{
    key1: T,
};

type Passenger<T> = array{
    key1: T,
};

type DeepStructure = {
    records: array<array{
        name: string,
        passengers: array<Passenger>,
    }>
};

type IntOrStr = int | string;
```

**Comment by mholubowski** [comment]
@klesun 

Wanted to bring these to your attention:
- https://psalm.dev/articles/conditional-love (released 2 weeks ago)
- https://psalm.dev/docs/running_psalm/plugins/authoring_plugins/ (potential path of integrating with psalm

**Comment by klesun** [comment]
A small summary on all the three analyzers and their extensions:
- phpstan, among alive ones, has [PHP Static Analysis](https://marketplace.visualstudio.com/items?itemName=breezelin.phpstan) extension, which seems to work ok with a [phpstan.neon](https://phpstan.org/config-reference) ~~yaml-ish~~ [neon](https://ne-on.org/) config file. You can [declare/reuse typedefs](https://phpstan.org/writing-php-code/phpdoc-types#type-aliases) in the config file like this:
    ```yaml
    parameters:
      level: 7
      typeAliases:    
        Name: 'string'    
        NameResolver: 'callable(): string'    
        NameOrResolver: 'Name|NameResolver'
    ```
    For complex typedefs you can use neon's `'''` to express [multi-line type strings](https://ne-on.org/)
    ```yaml
    parameters:
      level: 7
      typeAliases:    
        SomePurchase: '''
          array{
            id: int,
            amount: float,
            currency: string,
            product: string,
            dt: \DateTime,
          }
        '''
    ```

- In phan, as far as I could dig up, there does not exist an existing functionality to declare type aliases. There is this extension, though, for inline types only, that seems to work pretty ok: [PHP Phan (Analyzer)](https://marketplace.visualstudio.com/items?itemName=TysonAndre.php-phan)
- psalm has [Psalm (PHP Static Analysis Linting Machine)](https://marketplace.visualstudio.com/items?itemName=getpsalm.psalm-vscode-plugin) extension that highlights errors when you hit _ctrl+s_. Yet again confirmed that they don't have global typedefs yet, though file-scoped typedefs seem to work ok with the extension:
    ```
    /**
     * @psalm-type Product = array{id:int, name:string, ololo: float}
     */
    ```
